
data-collection:
  maps:
    # 单组柱状图
    "01001": '{"x":["北京","河北","山东","山西","河南","陕西","河北","海南","广州","广西"],"y":[1,2,5,4,2,3,2,3,4,2]}'
    "01001-legend": '["B1I"]'
    "01001-x": '["x"]'
    "01001-y": '["y"]'
    # 多组柱状图
    "01002": '{"x":["北京","河北","山东","山西","河南","海南","广州","广西"],"y1":[1,3,5,7,6,3,4,5],"y2":[2,2,6,5,8,2,3,6]}'
    "01002-legend": '["B1I","B2A"]'
    "01002-x": '["x"]'
    "01002-y": '["y1","y2"]'
    # 单组折线图
    "01003": '{"x":["北京","河北","山东","山西","河南","广州","广西"],"y":[6,2,3,10,5,3,4,2]}'
    "01003-legend": '["B1I"]'
    "01003-x": '["x"]'
    "01003-y": '["y"]'
    # 多组折线图
    "01004": '{"x":["北京","河北","山东","山西","河南","广东"],"y1":[1,2,1,4,5,10],"y2":[2,3,3,5,9,11]}'
    "01004-legend": '["B1I","B2A"]'
    "01004-x": '["x"]'
    "01004-y": '["y1","y2"]'
    # 饼图
    "01005": '{"x":["北京","河北","山东","山西","河南"],"y":[1,2,3,4,5]}'
    "01005-legend": '["北京","河北","山东","山西","河南"]'
    "01005-x": '["x"]'
    "01005-y": '["y"]'
    # 环图
    "01006": '{"x":["北京","河北","山东","山西","河南"],"y":[1,2,3,4,5]}'
    "01006-legend": '["北京","河北","山东","山西","河南"]'
    "01006-x": '["x"]'
    "01006-y": '["y"]'
    # 散点图
    "01007": '{"x":["北京","河北","山东","山西","河南"],"y":[1,2,3,4,5]}'
    "01007-legend": '["北京","河北","山东","山西","河南"]'
    "01007-x": '["x"]'
    "01007-y": '["y"]'
    #地图
    "02001": '[{"x":116.56812,"y":40.218628,"v":1},{"x":87.537185,"y":43.864985,"v":2},{"x":91.069466,"y":29.706469,"v":3},{"x":104.021163,"y":30.569989,"v":4},{"x":113.219812,"y":23.186342,"v":5},{"x":110.129066,"y":20.09057,"v":6}]'
    "02001-x": "x"
    "02001-y": "y"
    "02001-v": "v"
    #文本
    "03001": "文本"
    "03001-size": 16
    "03001-color": "#000000"